#!/bin/bash
repo init --git-lfs --no-clone-bundle -u https://github.com/LineageOS/android.git -b refs/changes/42/433642/9 -g default,-darwin
mkdir -p vendor/extra && cp ~/.android/adbkey.pub vendor/extra/adbkey.pub
